name: CI/CD tests

on:
  push:
    branches: [ "cicd_413131" ]
  pull_request:
    branches: [ "cicd_413131" ]

jobs:
  test_ubuntu-latest
    name:test_ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Rep in Ubuntu
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@V3
        with:
          python-version: 3.10
          architecture: x64
      - name: Run Tests in Ubuntu
        run : |
          python3 -m unittest "circle\_tests.py"
          python3 -m unittest "rectangle\_tests.py"
          python3 -m unittest "square\_tests.py"
          python3 -m unittest "triangle\_tests.py"

  test_windows-latest
    name:test_ubuntu
    runs-on: windows-latest
    steps:
      - name: Checkout Rep in Ubuntu
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@V3
        with:
          python-version: 3.10
          architecture: x64
      - name: Run Tests in Windows
        run : |
          python -m unittest "circle\_tests.py"
          python -m unittest "rectangle\_tests.py"
          python -m unittest "square\_tests.py"
          python -m unittest "triangle\_tests.py"

